name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (make sure to set up Docker Hub credentials in GitHub Secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image and tag it with the repo name and latest tag
      - name: Build Docker image
        run: |
          docker build -t  medo744/jwt:${{ github.sha }} .
          docker tag medo744/jwt:${{ github.sha }} medo744/jwt:latest

      # Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push medo744/jwt:${{ github.sha }}
          docker push medo744/jwt:latest
